--消费记录表
CREATE TABLE `expense_calendar` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT DEFAULT NULL,
	`name` VARCHAR ( 20 ) DEFAULT NULL,
	`saving_system` VARCHAR ( 20 ) DEFAULT NULL,
	`saving_system_id` INT DEFAULT NULL,
	`consume_mode` INT DEFAULT NULL COMMENT '1 消费 2 存入',
	`money` DOUBLE DEFAULT NULL,
	`detail` VARCHAR ( 100 ) DEFAULT NULL,
	`consume_time` TIMESTAMP NULL DEFAULT NULL,
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 116 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
--用户表
CREATE TABLE `user_info` (
	`user_id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR ( 20 ) DEFAULT NULL,
	`password` VARCHAR ( 32 ) DEFAULT NULL,
	`wight` INT DEFAULT NULL,
	`is_login` INT DEFAULT NULL,
	`last_login_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( `user_id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 4 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
--用户存款表
CREATE TABLE `user_savings` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT DEFAULT NULL,
	`saving_system` VARCHAR ( 20 ) DEFAULT NULL,
	`balance` DOUBLE DEFAULT NULL,
	`update_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ( `id` ) 
) ENGINE = INNODB AUTO_INCREMENT = 15 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
